version: 2

jobs:
  build:
    docker:
      - image: michaelth/node-chrome
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - node_modules-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            - node_modules-

      - run: npm install

      - save_cache:
          key: node_modules-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: Running tests
          command: npm test --headless

      - run:
          name: Publish to npm
          command: scripts/publish.sh
